# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'markers.ui'
#
# Created: Fri Jan 23 14:31:32 2015
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(318, 201)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxMarker = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMarker.sizePolicy().hasHeightForWidth())
        self.groupBoxMarker.setSizePolicy(sizePolicy)
        self.groupBoxMarker.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBoxMarker.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBoxMarker.setObjectName("groupBoxMarker")
        self.horizontalLayoutMarker = QtGui.QVBoxLayout(self.groupBoxMarker)
        self.horizontalLayoutMarker.setObjectName("horizontalLayoutMarker")
        self.horizontalLayout_Marker1 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1.setObjectName("horizontalLayout_Marker1")
        self.pushButtonMarker1 = QtGui.QPushButton(self.groupBoxMarker)
        self.pushButtonMarker1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMarker1.sizePolicy().hasHeightForWidth())
        self.pushButtonMarker1.setSizePolicy(sizePolicy)
        self.pushButtonMarker1.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker1.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker1.setStyleSheet("color: #0080FF")
        self.pushButtonMarker1.setCheckable(True)
        self.pushButtonMarker1.setObjectName("pushButtonMarker1")
        self.horizontalLayout_Marker1.addWidget(self.pushButtonMarker1)
        self.horizontalLayout_Marker1X = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1X.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_Marker1X.setObjectName("horizontalLayout_Marker1X")
        self.label_Marker1X = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1X.sizePolicy().hasHeightForWidth())
        self.label_Marker1X.setSizePolicy(sizePolicy)
        self.label_Marker1X.setStyleSheet("color: #0080FF")
        self.label_Marker1X.setObjectName("label_Marker1X")
        self.horizontalLayout_Marker1X.addWidget(self.label_Marker1X)
        self.Disp_Xmark1 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Xmark1.sizePolicy().hasHeightForWidth())
        self.Disp_Xmark1.setSizePolicy(sizePolicy)
        self.Disp_Xmark1.setAccessibleName("")
        self.Disp_Xmark1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Xmark1.setObjectName("Disp_Xmark1")
        self.horizontalLayout_Marker1X.addWidget(self.Disp_Xmark1)
        self.horizontalLayout_Marker1.addLayout(self.horizontalLayout_Marker1X)
        self.horizontalLayout_Marker1Y = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1Y.setObjectName("horizontalLayout_Marker1Y")
        self.label_Marker1Y = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1Y.sizePolicy().hasHeightForWidth())
        self.label_Marker1Y.setSizePolicy(sizePolicy)
        self.label_Marker1Y.setStyleSheet("color: #0080FF")
        self.label_Marker1Y.setObjectName("label_Marker1Y")
        self.horizontalLayout_Marker1Y.addWidget(self.label_Marker1Y)
        self.Disp_Ymark1 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Ymark1.sizePolicy().hasHeightForWidth())
        self.Disp_Ymark1.setSizePolicy(sizePolicy)
        self.Disp_Ymark1.setAccessibleName("")
        self.Disp_Ymark1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Ymark1.setObjectName("Disp_Ymark1")
        self.horizontalLayout_Marker1Y.addWidget(self.Disp_Ymark1)
        self.horizontalLayout_Marker1.addLayout(self.horizontalLayout_Marker1Y)
        self.horizontalLayoutMarker.addLayout(self.horizontalLayout_Marker1)
        self.horizontalLayout_Marker1_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1_2.setObjectName("horizontalLayout_Marker1_2")
        self.pushButtonMarker2 = QtGui.QPushButton(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMarker2.sizePolicy().hasHeightForWidth())
        self.pushButtonMarker2.setSizePolicy(sizePolicy)
        self.pushButtonMarker2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker2.setStyleSheet("color: red")
        self.pushButtonMarker2.setCheckable(True)
        self.pushButtonMarker2.setObjectName("pushButtonMarker2")
        self.horizontalLayout_Marker1_2.addWidget(self.pushButtonMarker2)
        self.horizontalLayout_Marker1X_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1X_2.setObjectName("horizontalLayout_Marker1X_2")
        self.label_Marker1X_2 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1X_2.sizePolicy().hasHeightForWidth())
        self.label_Marker1X_2.setSizePolicy(sizePolicy)
        self.label_Marker1X_2.setStyleSheet("color: red")
        self.label_Marker1X_2.setObjectName("label_Marker1X_2")
        self.horizontalLayout_Marker1X_2.addWidget(self.label_Marker1X_2)
        self.Disp_Xmark2 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Xmark2.sizePolicy().hasHeightForWidth())
        self.Disp_Xmark2.setSizePolicy(sizePolicy)
        self.Disp_Xmark2.setAccessibleName("")
        self.Disp_Xmark2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Xmark2.setObjectName("Disp_Xmark2")
        self.horizontalLayout_Marker1X_2.addWidget(self.Disp_Xmark2)
        self.horizontalLayout_Marker1_2.addLayout(self.horizontalLayout_Marker1X_2)
        self.horizontalLayout_Marker1Y_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1Y_2.setObjectName("horizontalLayout_Marker1Y_2")
        self.label_Marker1Y_2 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1Y_2.sizePolicy().hasHeightForWidth())
        self.label_Marker1Y_2.setSizePolicy(sizePolicy)
        self.label_Marker1Y_2.setStyleSheet("color: red")
        self.label_Marker1Y_2.setObjectName("label_Marker1Y_2")
        self.horizontalLayout_Marker1Y_2.addWidget(self.label_Marker1Y_2)
        self.Disp_Ymark2 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Ymark2.sizePolicy().hasHeightForWidth())
        self.Disp_Ymark2.setSizePolicy(sizePolicy)
        self.Disp_Ymark2.setAccessibleName("")
        self.Disp_Ymark2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Ymark2.setObjectName("Disp_Ymark2")
        self.horizontalLayout_Marker1Y_2.addWidget(self.Disp_Ymark2)
        self.horizontalLayout_Marker1_2.addLayout(self.horizontalLayout_Marker1Y_2)
        self.horizontalLayoutMarker.addLayout(self.horizontalLayout_Marker1_2)
        self.horizontalLayout_Marker1_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1_3.setObjectName("horizontalLayout_Marker1_3")
        self.pushButtonMarker3 = QtGui.QPushButton(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMarker3.sizePolicy().hasHeightForWidth())
        self.pushButtonMarker3.setSizePolicy(sizePolicy)
        self.pushButtonMarker3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker3.setStyleSheet("color: #00CCCC")
        self.pushButtonMarker3.setCheckable(True)
        self.pushButtonMarker3.setObjectName("pushButtonMarker3")
        self.horizontalLayout_Marker1_3.addWidget(self.pushButtonMarker3)
        self.horizontalLayout_Marker1X_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1X_3.setObjectName("horizontalLayout_Marker1X_3")
        self.label_Marker1X_3 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1X_3.sizePolicy().hasHeightForWidth())
        self.label_Marker1X_3.setSizePolicy(sizePolicy)
        self.label_Marker1X_3.setStyleSheet("color: #00CCCC")
        self.label_Marker1X_3.setObjectName("label_Marker1X_3")
        self.horizontalLayout_Marker1X_3.addWidget(self.label_Marker1X_3)
        self.Disp_Xmark3 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Xmark3.sizePolicy().hasHeightForWidth())
        self.Disp_Xmark3.setSizePolicy(sizePolicy)
        self.Disp_Xmark3.setAccessibleName("")
        self.Disp_Xmark3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Xmark3.setObjectName("Disp_Xmark3")
        self.horizontalLayout_Marker1X_3.addWidget(self.Disp_Xmark3)
        self.horizontalLayout_Marker1_3.addLayout(self.horizontalLayout_Marker1X_3)
        self.horizontalLayout_Marker1Y_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1Y_3.setObjectName("horizontalLayout_Marker1Y_3")
        self.label_Marker1Y_3 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1Y_3.sizePolicy().hasHeightForWidth())
        self.label_Marker1Y_3.setSizePolicy(sizePolicy)
        self.label_Marker1Y_3.setStyleSheet("color: #00CCCC")
        self.label_Marker1Y_3.setObjectName("label_Marker1Y_3")
        self.horizontalLayout_Marker1Y_3.addWidget(self.label_Marker1Y_3)
        self.Disp_Ymark3 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Ymark3.sizePolicy().hasHeightForWidth())
        self.Disp_Ymark3.setSizePolicy(sizePolicy)
        self.Disp_Ymark3.setAccessibleName("")
        self.Disp_Ymark3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Ymark3.setObjectName("Disp_Ymark3")
        self.horizontalLayout_Marker1Y_3.addWidget(self.Disp_Ymark3)
        self.horizontalLayout_Marker1_3.addLayout(self.horizontalLayout_Marker1Y_3)
        self.horizontalLayoutMarker.addLayout(self.horizontalLayout_Marker1_3)
        self.horizontalLayout_Marker1_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1_4.setObjectName("horizontalLayout_Marker1_4")
        self.pushButtonMarker4 = QtGui.QPushButton(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMarker4.sizePolicy().hasHeightForWidth())
        self.pushButtonMarker4.setSizePolicy(sizePolicy)
        self.pushButtonMarker4.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker4.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker4.setStyleSheet("color: #CC00CC")
        self.pushButtonMarker4.setCheckable(True)
        self.pushButtonMarker4.setObjectName("pushButtonMarker4")
        self.horizontalLayout_Marker1_4.addWidget(self.pushButtonMarker4)
        self.horizontalLayout_Marker1X_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1X_4.setObjectName("horizontalLayout_Marker1X_4")
        self.label_Marker1X_4 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1X_4.sizePolicy().hasHeightForWidth())
        self.label_Marker1X_4.setSizePolicy(sizePolicy)
        self.label_Marker1X_4.setStyleSheet("color: #CC00CC")
        self.label_Marker1X_4.setObjectName("label_Marker1X_4")
        self.horizontalLayout_Marker1X_4.addWidget(self.label_Marker1X_4)
        self.Disp_Xmark4 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Xmark4.sizePolicy().hasHeightForWidth())
        self.Disp_Xmark4.setSizePolicy(sizePolicy)
        self.Disp_Xmark4.setAccessibleName("")
        self.Disp_Xmark4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Xmark4.setObjectName("Disp_Xmark4")
        self.horizontalLayout_Marker1X_4.addWidget(self.Disp_Xmark4)
        self.horizontalLayout_Marker1_4.addLayout(self.horizontalLayout_Marker1X_4)
        self.horizontalLayout_Marker1Y_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1Y_4.setObjectName("horizontalLayout_Marker1Y_4")
        self.label_Marker1Y_4 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1Y_4.sizePolicy().hasHeightForWidth())
        self.label_Marker1Y_4.setSizePolicy(sizePolicy)
        self.label_Marker1Y_4.setStyleSheet("color: #CC00CC")
        self.label_Marker1Y_4.setObjectName("label_Marker1Y_4")
        self.horizontalLayout_Marker1Y_4.addWidget(self.label_Marker1Y_4)
        self.Disp_Ymark4 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Ymark4.sizePolicy().hasHeightForWidth())
        self.Disp_Ymark4.setSizePolicy(sizePolicy)
        self.Disp_Ymark4.setAccessibleName("")
        self.Disp_Ymark4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Ymark4.setObjectName("Disp_Ymark4")
        self.horizontalLayout_Marker1Y_4.addWidget(self.Disp_Ymark4)
        self.horizontalLayout_Marker1_4.addLayout(self.horizontalLayout_Marker1Y_4)
        self.horizontalLayoutMarker.addLayout(self.horizontalLayout_Marker1_4)
        self.verticalLayout.addWidget(self.groupBoxMarker)
        self.label_Marker1X.setBuddy(self.Disp_Xmark2)
        self.label_Marker1Y.setBuddy(self.Disp_Ymark2)
        self.label_Marker1X_2.setBuddy(self.Disp_Xmark2)
        self.label_Marker1Y_2.setBuddy(self.Disp_Ymark2)
        self.label_Marker1X_3.setBuddy(self.Disp_Xmark2)
        self.label_Marker1Y_3.setBuddy(self.Disp_Ymark2)
        self.label_Marker1X_4.setBuddy(self.Disp_Xmark2)
        self.label_Marker1Y_4.setBuddy(self.Disp_Ymark2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxMarker.setTitle(QtGui.QApplication.translate("Dialog", "Marker", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMarker1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Marker1X.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.Disp_Xmark1.setText(QtGui.QApplication.translate("Dialog", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Marker1Y.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.Disp_Ymark1.setText(QtGui.QApplication.translate("Dialog", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMarker2.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Marker1X_2.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.Disp_Xmark2.setText(QtGui.QApplication.translate("Dialog", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Marker1Y_2.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.Disp_Ymark2.setText(QtGui.QApplication.translate("Dialog", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMarker3.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Marker1X_3.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.Disp_Xmark3.setText(QtGui.QApplication.translate("Dialog", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Marker1Y_3.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.Disp_Ymark3.setText(QtGui.QApplication.translate("Dialog", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMarker4.setText(QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Marker1X_4.setText(QtGui.QApplication.translate("Dialog", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.Disp_Xmark4.setText(QtGui.QApplication.translate("Dialog", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Marker1Y_4.setText(QtGui.QApplication.translate("Dialog", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.Disp_Ymark4.setText(QtGui.QApplication.translate("Dialog", "512", None, QtGui.QApplication.UnicodeUTF8))

