# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'markers.ui'
#
# Created: Mon Sep 15 15:38:31 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(318, 201)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBoxMarker = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxMarker.sizePolicy().hasHeightForWidth())
        self.groupBoxMarker.setSizePolicy(sizePolicy)
        self.groupBoxMarker.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBoxMarker.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBoxMarker.setObjectName(_fromUtf8("groupBoxMarker"))
        self.horizontalLayoutMarker = QtGui.QVBoxLayout(self.groupBoxMarker)
        self.horizontalLayoutMarker.setObjectName(_fromUtf8("horizontalLayoutMarker"))
        self.horizontalLayout_Marker1 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1.setObjectName(_fromUtf8("horizontalLayout_Marker1"))
        self.pushButtonMarker1 = QtGui.QPushButton(self.groupBoxMarker)
        self.pushButtonMarker1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMarker1.sizePolicy().hasHeightForWidth())
        self.pushButtonMarker1.setSizePolicy(sizePolicy)
        self.pushButtonMarker1.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker1.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker1.setStyleSheet(_fromUtf8("color: #0080FF"))
        self.pushButtonMarker1.setCheckable(True)
        self.pushButtonMarker1.setObjectName(_fromUtf8("pushButtonMarker1"))
        self.horizontalLayout_Marker1.addWidget(self.pushButtonMarker1)
        self.horizontalLayout_Marker1X = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1X.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_Marker1X.setObjectName(_fromUtf8("horizontalLayout_Marker1X"))
        self.label_Marker1X = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1X.sizePolicy().hasHeightForWidth())
        self.label_Marker1X.setSizePolicy(sizePolicy)
        self.label_Marker1X.setStyleSheet(_fromUtf8("color: #0080FF"))
        self.label_Marker1X.setObjectName(_fromUtf8("label_Marker1X"))
        self.horizontalLayout_Marker1X.addWidget(self.label_Marker1X)
        self.Disp_Xmark1 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Xmark1.sizePolicy().hasHeightForWidth())
        self.Disp_Xmark1.setSizePolicy(sizePolicy)
        self.Disp_Xmark1.setAccessibleName(_fromUtf8(""))
        self.Disp_Xmark1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Xmark1.setObjectName(_fromUtf8("Disp_Xmark1"))
        self.horizontalLayout_Marker1X.addWidget(self.Disp_Xmark1)
        self.horizontalLayout_Marker1.addLayout(self.horizontalLayout_Marker1X)
        self.horizontalLayout_Marker1Y = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1Y.setObjectName(_fromUtf8("horizontalLayout_Marker1Y"))
        self.label_Marker1Y = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1Y.sizePolicy().hasHeightForWidth())
        self.label_Marker1Y.setSizePolicy(sizePolicy)
        self.label_Marker1Y.setStyleSheet(_fromUtf8("color: #0080FF"))
        self.label_Marker1Y.setObjectName(_fromUtf8("label_Marker1Y"))
        self.horizontalLayout_Marker1Y.addWidget(self.label_Marker1Y)
        self.Disp_Ymark1 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Ymark1.sizePolicy().hasHeightForWidth())
        self.Disp_Ymark1.setSizePolicy(sizePolicy)
        self.Disp_Ymark1.setAccessibleName(_fromUtf8(""))
        self.Disp_Ymark1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Ymark1.setObjectName(_fromUtf8("Disp_Ymark1"))
        self.horizontalLayout_Marker1Y.addWidget(self.Disp_Ymark1)
        self.horizontalLayout_Marker1.addLayout(self.horizontalLayout_Marker1Y)
        self.horizontalLayoutMarker.addLayout(self.horizontalLayout_Marker1)
        self.horizontalLayout_Marker1_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1_2.setObjectName(_fromUtf8("horizontalLayout_Marker1_2"))
        self.pushButtonMarker2 = QtGui.QPushButton(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMarker2.sizePolicy().hasHeightForWidth())
        self.pushButtonMarker2.setSizePolicy(sizePolicy)
        self.pushButtonMarker2.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker2.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker2.setStyleSheet(_fromUtf8("color: red"))
        self.pushButtonMarker2.setCheckable(True)
        self.pushButtonMarker2.setObjectName(_fromUtf8("pushButtonMarker2"))
        self.horizontalLayout_Marker1_2.addWidget(self.pushButtonMarker2)
        self.horizontalLayout_Marker1X_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1X_2.setObjectName(_fromUtf8("horizontalLayout_Marker1X_2"))
        self.label_Marker1X_2 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1X_2.sizePolicy().hasHeightForWidth())
        self.label_Marker1X_2.setSizePolicy(sizePolicy)
        self.label_Marker1X_2.setStyleSheet(_fromUtf8("color: red"))
        self.label_Marker1X_2.setObjectName(_fromUtf8("label_Marker1X_2"))
        self.horizontalLayout_Marker1X_2.addWidget(self.label_Marker1X_2)
        self.Disp_Xmark2 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Xmark2.sizePolicy().hasHeightForWidth())
        self.Disp_Xmark2.setSizePolicy(sizePolicy)
        self.Disp_Xmark2.setAccessibleName(_fromUtf8(""))
        self.Disp_Xmark2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Xmark2.setObjectName(_fromUtf8("Disp_Xmark2"))
        self.horizontalLayout_Marker1X_2.addWidget(self.Disp_Xmark2)
        self.horizontalLayout_Marker1_2.addLayout(self.horizontalLayout_Marker1X_2)
        self.horizontalLayout_Marker1Y_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1Y_2.setObjectName(_fromUtf8("horizontalLayout_Marker1Y_2"))
        self.label_Marker1Y_2 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1Y_2.sizePolicy().hasHeightForWidth())
        self.label_Marker1Y_2.setSizePolicy(sizePolicy)
        self.label_Marker1Y_2.setStyleSheet(_fromUtf8("color: red"))
        self.label_Marker1Y_2.setObjectName(_fromUtf8("label_Marker1Y_2"))
        self.horizontalLayout_Marker1Y_2.addWidget(self.label_Marker1Y_2)
        self.Disp_Ymark2 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Ymark2.sizePolicy().hasHeightForWidth())
        self.Disp_Ymark2.setSizePolicy(sizePolicy)
        self.Disp_Ymark2.setAccessibleName(_fromUtf8(""))
        self.Disp_Ymark2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Ymark2.setObjectName(_fromUtf8("Disp_Ymark2"))
        self.horizontalLayout_Marker1Y_2.addWidget(self.Disp_Ymark2)
        self.horizontalLayout_Marker1_2.addLayout(self.horizontalLayout_Marker1Y_2)
        self.horizontalLayoutMarker.addLayout(self.horizontalLayout_Marker1_2)
        self.horizontalLayout_Marker1_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1_3.setObjectName(_fromUtf8("horizontalLayout_Marker1_3"))
        self.pushButtonMarker3 = QtGui.QPushButton(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMarker3.sizePolicy().hasHeightForWidth())
        self.pushButtonMarker3.setSizePolicy(sizePolicy)
        self.pushButtonMarker3.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker3.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker3.setStyleSheet(_fromUtf8("color: #00CCCC"))
        self.pushButtonMarker3.setCheckable(True)
        self.pushButtonMarker3.setObjectName(_fromUtf8("pushButtonMarker3"))
        self.horizontalLayout_Marker1_3.addWidget(self.pushButtonMarker3)
        self.horizontalLayout_Marker1X_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1X_3.setObjectName(_fromUtf8("horizontalLayout_Marker1X_3"))
        self.label_Marker1X_3 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1X_3.sizePolicy().hasHeightForWidth())
        self.label_Marker1X_3.setSizePolicy(sizePolicy)
        self.label_Marker1X_3.setStyleSheet(_fromUtf8("color: #00CCCC"))
        self.label_Marker1X_3.setObjectName(_fromUtf8("label_Marker1X_3"))
        self.horizontalLayout_Marker1X_3.addWidget(self.label_Marker1X_3)
        self.Disp_Xmark3 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Xmark3.sizePolicy().hasHeightForWidth())
        self.Disp_Xmark3.setSizePolicy(sizePolicy)
        self.Disp_Xmark3.setAccessibleName(_fromUtf8(""))
        self.Disp_Xmark3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Xmark3.setObjectName(_fromUtf8("Disp_Xmark3"))
        self.horizontalLayout_Marker1X_3.addWidget(self.Disp_Xmark3)
        self.horizontalLayout_Marker1_3.addLayout(self.horizontalLayout_Marker1X_3)
        self.horizontalLayout_Marker1Y_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1Y_3.setObjectName(_fromUtf8("horizontalLayout_Marker1Y_3"))
        self.label_Marker1Y_3 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1Y_3.sizePolicy().hasHeightForWidth())
        self.label_Marker1Y_3.setSizePolicy(sizePolicy)
        self.label_Marker1Y_3.setStyleSheet(_fromUtf8("color: #00CCCC"))
        self.label_Marker1Y_3.setObjectName(_fromUtf8("label_Marker1Y_3"))
        self.horizontalLayout_Marker1Y_3.addWidget(self.label_Marker1Y_3)
        self.Disp_Ymark3 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Ymark3.sizePolicy().hasHeightForWidth())
        self.Disp_Ymark3.setSizePolicy(sizePolicy)
        self.Disp_Ymark3.setAccessibleName(_fromUtf8(""))
        self.Disp_Ymark3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Ymark3.setObjectName(_fromUtf8("Disp_Ymark3"))
        self.horizontalLayout_Marker1Y_3.addWidget(self.Disp_Ymark3)
        self.horizontalLayout_Marker1_3.addLayout(self.horizontalLayout_Marker1Y_3)
        self.horizontalLayoutMarker.addLayout(self.horizontalLayout_Marker1_3)
        self.horizontalLayout_Marker1_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1_4.setObjectName(_fromUtf8("horizontalLayout_Marker1_4"))
        self.pushButtonMarker4 = QtGui.QPushButton(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMarker4.sizePolicy().hasHeightForWidth())
        self.pushButtonMarker4.setSizePolicy(sizePolicy)
        self.pushButtonMarker4.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker4.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButtonMarker4.setStyleSheet(_fromUtf8("color: #CC00CC"))
        self.pushButtonMarker4.setCheckable(True)
        self.pushButtonMarker4.setObjectName(_fromUtf8("pushButtonMarker4"))
        self.horizontalLayout_Marker1_4.addWidget(self.pushButtonMarker4)
        self.horizontalLayout_Marker1X_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1X_4.setObjectName(_fromUtf8("horizontalLayout_Marker1X_4"))
        self.label_Marker1X_4 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1X_4.sizePolicy().hasHeightForWidth())
        self.label_Marker1X_4.setSizePolicy(sizePolicy)
        self.label_Marker1X_4.setStyleSheet(_fromUtf8("color: #CC00CC"))
        self.label_Marker1X_4.setObjectName(_fromUtf8("label_Marker1X_4"))
        self.horizontalLayout_Marker1X_4.addWidget(self.label_Marker1X_4)
        self.Disp_Xmark4 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Xmark4.sizePolicy().hasHeightForWidth())
        self.Disp_Xmark4.setSizePolicy(sizePolicy)
        self.Disp_Xmark4.setAccessibleName(_fromUtf8(""))
        self.Disp_Xmark4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Xmark4.setObjectName(_fromUtf8("Disp_Xmark4"))
        self.horizontalLayout_Marker1X_4.addWidget(self.Disp_Xmark4)
        self.horizontalLayout_Marker1_4.addLayout(self.horizontalLayout_Marker1X_4)
        self.horizontalLayout_Marker1Y_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_Marker1Y_4.setObjectName(_fromUtf8("horizontalLayout_Marker1Y_4"))
        self.label_Marker1Y_4 = QtGui.QLabel(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Marker1Y_4.sizePolicy().hasHeightForWidth())
        self.label_Marker1Y_4.setSizePolicy(sizePolicy)
        self.label_Marker1Y_4.setStyleSheet(_fromUtf8("color: #CC00CC"))
        self.label_Marker1Y_4.setObjectName(_fromUtf8("label_Marker1Y_4"))
        self.horizontalLayout_Marker1Y_4.addWidget(self.label_Marker1Y_4)
        self.Disp_Ymark4 = QtGui.QLineEdit(self.groupBoxMarker)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Disp_Ymark4.sizePolicy().hasHeightForWidth())
        self.Disp_Ymark4.setSizePolicy(sizePolicy)
        self.Disp_Ymark4.setAccessibleName(_fromUtf8(""))
        self.Disp_Ymark4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Disp_Ymark4.setObjectName(_fromUtf8("Disp_Ymark4"))
        self.horizontalLayout_Marker1Y_4.addWidget(self.Disp_Ymark4)
        self.horizontalLayout_Marker1_4.addLayout(self.horizontalLayout_Marker1Y_4)
        self.horizontalLayoutMarker.addLayout(self.horizontalLayout_Marker1_4)
        self.verticalLayout.addWidget(self.groupBoxMarker)
        self.label_Marker1X.setBuddy(self.Disp_Xmark2)
        self.label_Marker1Y.setBuddy(self.Disp_Ymark2)
        self.label_Marker1X_2.setBuddy(self.Disp_Xmark2)
        self.label_Marker1Y_2.setBuddy(self.Disp_Ymark2)
        self.label_Marker1X_3.setBuddy(self.Disp_Xmark2)
        self.label_Marker1Y_3.setBuddy(self.Disp_Ymark2)
        self.label_Marker1X_4.setBuddy(self.Disp_Xmark2)
        self.label_Marker1Y_4.setBuddy(self.Disp_Ymark2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBoxMarker.setTitle(_translate("Dialog", "Marker", None))
        self.pushButtonMarker1.setText(_translate("Dialog", "1", None))
        self.label_Marker1X.setText(_translate("Dialog", "X", None))
        self.Disp_Xmark1.setText(_translate("Dialog", "512", None))
        self.label_Marker1Y.setText(_translate("Dialog", "Y", None))
        self.Disp_Ymark1.setText(_translate("Dialog", "512", None))
        self.pushButtonMarker2.setText(_translate("Dialog", "2", None))
        self.label_Marker1X_2.setText(_translate("Dialog", "X", None))
        self.Disp_Xmark2.setText(_translate("Dialog", "512", None))
        self.label_Marker1Y_2.setText(_translate("Dialog", "Y", None))
        self.Disp_Ymark2.setText(_translate("Dialog", "512", None))
        self.pushButtonMarker3.setText(_translate("Dialog", "3", None))
        self.label_Marker1X_3.setText(_translate("Dialog", "X", None))
        self.Disp_Xmark3.setText(_translate("Dialog", "512", None))
        self.label_Marker1Y_3.setText(_translate("Dialog", "Y", None))
        self.Disp_Ymark3.setText(_translate("Dialog", "512", None))
        self.pushButtonMarker4.setText(_translate("Dialog", "4", None))
        self.label_Marker1X_4.setText(_translate("Dialog", "X", None))
        self.Disp_Xmark4.setText(_translate("Dialog", "512", None))
        self.label_Marker1Y_4.setText(_translate("Dialog", "Y", None))
        self.Disp_Ymark4.setText(_translate("Dialog", "512", None))

