# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'specific.ui'
#
# Created: Wed Dec 10 14:32:39 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(318, 665)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gigeBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gigeBox.sizePolicy().hasHeightForWidth())
        self.gigeBox.setSizePolicy(sizePolicy)
        self.gigeBox.setMinimumSize(QtCore.QSize(300, 0))
        self.gigeBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.gigeBox.setObjectName(_fromUtf8("gigeBox"))
        self.gridLayout = QtGui.QGridLayout(self.gigeBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cmlabelG = QtGui.QLabel(self.gigeBox)
        self.cmlabelG.setObjectName(_fromUtf8("cmlabelG"))
        self.gridLayout.addWidget(self.cmlabelG, 0, 0, 1, 1)
        self.cameramodeG = QtGui.QComboBox(self.gigeBox)
        self.cameramodeG.setObjectName(_fromUtf8("cameramodeG"))
        self.cameramodeG.addItem(_fromUtf8(""))
        self.cameramodeG.addItem(_fromUtf8(""))
        self.cameramodeG.addItem(_fromUtf8(""))
        self.cameramodeG.addItem(_fromUtf8(""))
        self.cameramodeG.addItem(_fromUtf8(""))
        self.cameramodeG.addItem(_fromUtf8(""))
        self.cameramodeG.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cameramodeG, 0, 2, 1, 1)
        self.gainlabel = QtGui.QLabel(self.gigeBox)
        self.gainlabel.setObjectName(_fromUtf8("gainlabel"))
        self.gridLayout.addWidget(self.gainlabel, 1, 0, 1, 1)
        self.gainG = QtGui.QLineEdit(self.gigeBox)
        self.gainG.setObjectName(_fromUtf8("gainG"))
        self.gridLayout.addWidget(self.gainG, 1, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.gigeBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 2)
        self.timeG = QtGui.QLineEdit(self.gigeBox)
        self.timeG.setObjectName(_fromUtf8("timeG"))
        self.gridLayout.addWidget(self.timeG, 2, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.gigeBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 2)
        self.periodG = QtGui.QLineEdit(self.gigeBox)
        self.periodG.setObjectName(_fromUtf8("periodG"))
        self.gridLayout.addWidget(self.periodG, 3, 2, 1, 1)
        self.runButtonG = QtGui.QPushButton(self.gigeBox)
        self.runButtonG.setCheckable(True)
        self.runButtonG.setObjectName(_fromUtf8("runButtonG"))
        self.gridLayout.addWidget(self.runButtonG, 4, 0, 1, 2)
        self.verticalLayout.addWidget(self.gigeBox)
        self.pulnixBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pulnixBox.sizePolicy().hasHeightForWidth())
        self.pulnixBox.setSizePolicy(sizePolicy)
        self.pulnixBox.setMinimumSize(QtCore.QSize(300, 0))
        self.pulnixBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.pulnixBox.setObjectName(_fromUtf8("pulnixBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.pulnixBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cmlabelP = QtGui.QLabel(self.pulnixBox)
        self.cmlabelP.setObjectName(_fromUtf8("cmlabelP"))
        self.gridLayout_2.addWidget(self.cmlabelP, 0, 0, 1, 1)
        self.cameramodeP = QtGui.QComboBox(self.pulnixBox)
        self.cameramodeP.setObjectName(_fromUtf8("cameramodeP"))
        self.cameramodeP.addItem(_fromUtf8(""))
        self.cameramodeP.addItem(_fromUtf8(""))
        self.cameramodeP.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.cameramodeP, 0, 2, 1, 1)
        self.gainlabel_2 = QtGui.QLabel(self.pulnixBox)
        self.gainlabel_2.setObjectName(_fromUtf8("gainlabel_2"))
        self.gridLayout_2.addWidget(self.gainlabel_2, 1, 0, 1, 2)
        self.gainAP = QtGui.QLineEdit(self.pulnixBox)
        self.gainAP.setObjectName(_fromUtf8("gainAP"))
        self.gridLayout_2.addWidget(self.gainAP, 1, 2, 1, 1)
        self.gainlabel_3 = QtGui.QLabel(self.pulnixBox)
        self.gainlabel_3.setObjectName(_fromUtf8("gainlabel_3"))
        self.gridLayout_2.addWidget(self.gainlabel_3, 2, 0, 1, 1)
        self.gainBP = QtGui.QLineEdit(self.pulnixBox)
        self.gainBP.setObjectName(_fromUtf8("gainBP"))
        self.gridLayout_2.addWidget(self.gainBP, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.pulnixBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 2)
        self.timeP = QtGui.QComboBox(self.pulnixBox)
        self.timeP.setObjectName(_fromUtf8("timeP"))
        self.timeP.addItem(_fromUtf8(""))
        self.timeP.addItem(_fromUtf8(""))
        self.timeP.addItem(_fromUtf8(""))
        self.timeP.addItem(_fromUtf8(""))
        self.timeP.addItem(_fromUtf8(""))
        self.timeP.addItem(_fromUtf8(""))
        self.timeP.addItem(_fromUtf8(""))
        self.timeP.addItem(_fromUtf8(""))
        self.timeP.addItem(_fromUtf8(""))
        self.timeP.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.timeP, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.pulnixBox)
        self.opalBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.opalBox.sizePolicy().hasHeightForWidth())
        self.opalBox.setSizePolicy(sizePolicy)
        self.opalBox.setMinimumSize(QtCore.QSize(300, 0))
        self.opalBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.opalBox.setObjectName(_fromUtf8("opalBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.opalBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cmlabelO = QtGui.QLabel(self.opalBox)
        self.cmlabelO.setObjectName(_fromUtf8("cmlabelO"))
        self.gridLayout_3.addWidget(self.cmlabelO, 0, 0, 1, 1)
        self.cameramodeO = QtGui.QComboBox(self.opalBox)
        self.cameramodeO.setObjectName(_fromUtf8("cameramodeO"))
        self.cameramodeO.addItem(_fromUtf8(""))
        self.cameramodeO.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.cameramodeO, 0, 3, 1, 1)
        self.gainlabel_4 = QtGui.QLabel(self.opalBox)
        self.gainlabel_4.setObjectName(_fromUtf8("gainlabel_4"))
        self.gridLayout_3.addWidget(self.gainlabel_4, 1, 0, 1, 2)
        self.gainO = QtGui.QLineEdit(self.opalBox)
        self.gainO.setObjectName(_fromUtf8("gainO"))
        self.gridLayout_3.addWidget(self.gainO, 1, 3, 1, 1)
        self.label_10 = QtGui.QLabel(self.opalBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 0, 1, 2)
        self.timeO = QtGui.QLineEdit(self.opalBox)
        self.timeO.setObjectName(_fromUtf8("timeO"))
        self.gridLayout_3.addWidget(self.timeO, 2, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.opalBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 3, 0, 1, 3)
        self.periodO = QtGui.QLineEdit(self.opalBox)
        self.periodO.setObjectName(_fromUtf8("periodO"))
        self.gridLayout_3.addWidget(self.periodO, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.opalBox)
        self.up900Box = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.up900Box.sizePolicy().hasHeightForWidth())
        self.up900Box.setSizePolicy(sizePolicy)
        self.up900Box.setMinimumSize(QtCore.QSize(300, 0))
        self.up900Box.setMaximumSize(QtCore.QSize(300, 16777215))
        self.up900Box.setObjectName(_fromUtf8("up900Box"))
        self.gridLayout_4 = QtGui.QGridLayout(self.up900Box)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gainlabel_5 = QtGui.QLabel(self.up900Box)
        self.gainlabel_5.setObjectName(_fromUtf8("gainlabel_5"))
        self.gridLayout_4.addWidget(self.gainlabel_5, 0, 0, 1, 1)
        self.gainU = QtGui.QLineEdit(self.up900Box)
        self.gainU.setObjectName(_fromUtf8("gainU"))
        self.gridLayout_4.addWidget(self.gainU, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.up900Box)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 1, 0, 1, 1)
        self.timeU = QtGui.QComboBox(self.up900Box)
        self.timeU.setObjectName(_fromUtf8("timeU"))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.timeU.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.timeU, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.up900Box)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Apply|QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.gigeBox.setTitle(QtGui.QApplication.translate("Dialog", "GigE Camera Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.cmlabelG.setText(QtGui.QApplication.translate("Dialog", "Camera Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeG.setItemText(0, QtGui.QApplication.translate("Dialog", "Free Run", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeG.setItemText(1, QtGui.QApplication.translate("Dialog", "Sync In 1", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeG.setItemText(2, QtGui.QApplication.translate("Dialog", "Sync In 2", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeG.setItemText(3, QtGui.QApplication.translate("Dialog", "Sync In 3", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeG.setItemText(4, QtGui.QApplication.translate("Dialog", "Sync In 4", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeG.setItemText(5, QtGui.QApplication.translate("Dialog", "Fixed Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeG.setItemText(6, QtGui.QApplication.translate("Dialog", "Software", None, QtGui.QApplication.UnicodeUTF8))
        self.gainlabel.setText(QtGui.QApplication.translate("Dialog", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Acquisition Time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Acquisition Period (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.runButtonG.setText(QtGui.QApplication.translate("Dialog", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.pulnixBox.setTitle(QtGui.QApplication.translate("Dialog", "Pulnix Camera Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.cmlabelP.setText(QtGui.QApplication.translate("Dialog", "Camera Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeP.setItemText(0, QtGui.QApplication.translate("Dialog", "Async (Triggered)", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeP.setItemText(1, QtGui.QApplication.translate("Dialog", "Manual (Free Run)", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeP.setItemText(2, QtGui.QApplication.translate("Dialog", "Direct", None, QtGui.QApplication.UnicodeUTF8))
        self.gainlabel_2.setText(QtGui.QApplication.translate("Dialog", "Gain A (66-488)", None, QtGui.QApplication.UnicodeUTF8))
        self.gainlabel_3.setText(QtGui.QApplication.translate("Dialog", "Gain B (66-488)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Acquisition Time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.timeP.setItemText(0, QtGui.QApplication.translate("Dialog", "1/250", None, QtGui.QApplication.UnicodeUTF8))
        self.timeP.setItemText(1, QtGui.QApplication.translate("Dialog", "1/500", None, QtGui.QApplication.UnicodeUTF8))
        self.timeP.setItemText(2, QtGui.QApplication.translate("Dialog", "1/1000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeP.setItemText(3, QtGui.QApplication.translate("Dialog", "1/2000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeP.setItemText(4, QtGui.QApplication.translate("Dialog", "1/4000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeP.setItemText(5, QtGui.QApplication.translate("Dialog", "1/8000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeP.setItemText(6, QtGui.QApplication.translate("Dialog", "1/16000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeP.setItemText(7, QtGui.QApplication.translate("Dialog", "1/32000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeP.setItemText(8, QtGui.QApplication.translate("Dialog", "1/64000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeP.setItemText(9, QtGui.QApplication.translate("Dialog", "Pulse", None, QtGui.QApplication.UnicodeUTF8))
        self.opalBox.setTitle(QtGui.QApplication.translate("Dialog", "Opal Camera Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.cmlabelO.setText(QtGui.QApplication.translate("Dialog", "Camera Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeO.setItemText(0, QtGui.QApplication.translate("Dialog", "Free Run", None, QtGui.QApplication.UnicodeUTF8))
        self.cameramodeO.setItemText(1, QtGui.QApplication.translate("Dialog", "Normal (Triggered)", None, QtGui.QApplication.UnicodeUTF8))
        self.gainlabel_4.setText(QtGui.QApplication.translate("Dialog", "Gain (100-3200)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Acquisition Time (x 10us)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Acquisition Period (x 10us)", None, QtGui.QApplication.UnicodeUTF8))
        self.up900Box.setTitle(QtGui.QApplication.translate("Dialog", "Uniq UP-900 Camera Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.gainlabel_5.setText(QtGui.QApplication.translate("Dialog", "Gain (0 - 1023)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Acquisition Time (s)", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(0, QtGui.QApplication.translate("Dialog", "1/15", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(1, QtGui.QApplication.translate("Dialog", "1/30", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(2, QtGui.QApplication.translate("Dialog", "1/60", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(3, QtGui.QApplication.translate("Dialog", "1/125", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(4, QtGui.QApplication.translate("Dialog", "1/250", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(5, QtGui.QApplication.translate("Dialog", "1/500", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(6, QtGui.QApplication.translate("Dialog", "1/1000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(7, QtGui.QApplication.translate("Dialog", "1/2000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(8, QtGui.QApplication.translate("Dialog", "1/3000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(9, QtGui.QApplication.translate("Dialog", "1/4000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(10, QtGui.QApplication.translate("Dialog", "1/5000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(11, QtGui.QApplication.translate("Dialog", "1/6000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(12, QtGui.QApplication.translate("Dialog", "1/7500", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(13, QtGui.QApplication.translate("Dialog", "1/10000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(14, QtGui.QApplication.translate("Dialog", "1/15000", None, QtGui.QApplication.UnicodeUTF8))
        self.timeU.setItemText(15, QtGui.QApplication.translate("Dialog", "1/31000", None, QtGui.QApplication.UnicodeUTF8))

